spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardwareManager?createDatabaseIfNotExist=true
    username: root
    password: 03121518

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
